### ISSUE TITLE
rootio: add support for branches with multiple leaves

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#156]
consider the following ROOT file:

```
$> root-ls -t ./testdata/struct.root
=== [./testdata/struct.root] ===
version: 60303
TTree     test                    identical leaf names in different branches (entries=1)
  branch1 "intleaf/I:floatleaf/F" TBranch
  branch2 "intleaf/I:floatleaf/F" TBranch
```

it crashes when trying to dump it:
```
$> root-dump ./testdata/struct.root
>>> file[./testdata/struct.root]
key[000]: test;1 "identical leaf names in different branches" (TTree)
panic: invalid ptr type *int32 (leaf=floatleaf|*rootio.LeafF)

goroutine 1 [running]:
go-hep.org/x/hep/rootio.(*LeafF).scan(0xc0000babe0, 0xc000065680, 0x7318e0, 0xc000013978, 0x0, 0x0)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/rootio/leaf_gen.go:897 +0x4f9
go-hep.org/x/hep/rootio.(*tbranch).scan(0xc000186000, 0x7318e0, 0xc000013978, 0x0, 0x7)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/rootio/branch.go:389 +0xa3
go-hep.org/x/hep/rootio.(*Scanner).Scan(0xc0000badc0, 0x7e5410, 0xc0000badc0)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/rootio/scanner.go:482 +0x1f0
main.dumpTree(0x817080, 0xc00000e018, 0x81bb00, 0xc000169200, 0x0, 0x0)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/rootio/cmd/root-dump/main.go:161 +0x60f
main.dumpDir(0x817080, 0xc00000e018, 0x818520, 0xc0000a18c0, 0x1, 0x1, 0x1)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/rootio/cmd/root-dump/main.go:115 +0x47e
main.dump(0x817080, 0xc00000e018, 0x7fff83c8c6af, 0x21, 0x4db601, 0x0, 0x0)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/rootio/cmd/root-dump/main.go:101 +0x162
main.main()
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/rootio/cmd/root-dump/main.go:86 +0x111
```

**Comment by uzzielperez** [comment]
Hi @sbinet , I am curious if anyone has made any progress on this. I was also trying this out with uproot for my work. The curious thing is when I try to loop over the events with a python script, the script only picks up one of the leaves of the branches. Do you know why?

**Comment by sbinet** [comment]
Not much progress, I am afraid (PRs welcomed)
I am not completely surprised this doesn't work in uproot: uproot initial code was based on Groot :)

**Comment by sbinet** [comment]
hi @uzzielperez (and HNY-2020!)

dunno whether it's still relevant for your work, but #558 is adding preliminary support for properly reading trees with branches w/ multiple leaves.

see:
```
$> root-dump ./groot/testdata/root_numpy_struct.root 
>>> file[./groot/testdata/root_numpy_struct.root]
key[000]: test;1 "identical leaf names in different branches" (TTree)
[000][branch1]: 10
[000][branch1]: 15.5
[000][branch2]: 20
[000][branch2]: 781.2
```

I need to add a few more tests (_ie:_ w/ and w/o padding in the leaves) and also adapt `root-dump` output for multi-leaves branches.

**Comment by uzzielperez** [comment]
Hi @sbinet! Thanks! This is certainly welcome for my work! I will try it out.

**Comment by sbinet** [comment]
done.
