### ISSUE TITLE
root-srv fails to parse/plot plenty of histograms

### ISSUE THREAD

**Issue by vkuznet** [go-hep/hep#390]
I experience lots of issues with this file: /afs/cern.ch/user/v/valya/public/Tau_Run2017F-31Mar2018-v1_NANOAOD.root
Basically etc, phi plots for different attributes are not produced leading to runtime errors.

**Comment by vkuznet** [comment]
I updated my go-hep to recent versions, and then tried again. First, plot Electron_eta works fine, then I tried Electron_mass and got these type of runtime errors:
```
goroutine 37 [running]:
net/http.(*conn).serve.func1(0xc00032e1e0)
	/opt/local/lib/go/src/net/http/server.go:1746 +0xd0
panic(0x16e04c0, 0x20a2fd0)
	/opt/local/lib/go/src/runtime/panic.go:513 +0x1b9
go-hep.org/x/hep/rootio.(*LeafF).scan(0xc0418b68c0, 0xc0000760c0, 0x1685a80, 0xc00221a000, 0xc00221a000, 0x16)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/leaf_gen.go:991 +0x5b3
go-hep.org/x/hep/rootio.(*tbranch).scan(0xc0418b1dc0, 0x1685a80, 0xc00221a000, 0x1685a80, 0xc00221a000)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/branch.go:389 +0x9c
go-hep.org/x/hep/rootio.(*TreeScanner).scanArgs(0xc002ac0000, 0xc040fb1988, 0x1, 0x1, 0x0, 0xc040fb17b8)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/scanner.go:363 +0x297
go-hep.org/x/hep/rootio.(*TreeScanner).Scan(0xc002ac0000, 0xc040fb1988, 0x1, 0x1, 0x0, 0x0)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/scanner.go:333 +0x9b
go-hep.org/x/hep/rootio/cmd/root-srv/server.(*server).plotBranchHandle(0xc00014ba10, 0x19d5a80, 0xc002214000, 0xc00012c400, 0x0, 0x0)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/cmd/root-srv/server/plots.go:222 +0xb23
go-hep.org/x/hep/rootio/cmd/root-srv/server.(*server).plotBranchHandle-fm(0x19d5a80, 0xc002214000, 0xc00012c400, 0xc00012c400, 0x0)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/cmd/root-srv/server/server.go:42 +0x48
go-hep.org/x/hep/rootio/cmd/root-srv/server.(*server).wrap.func1(0x19d5a80, 0xc002214000, 0xc00012c400)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/cmd/root-srv/server/server.go:90 +0x171
net/http.HandlerFunc.ServeHTTP(0xc000224880, 0x19d5a80, 0xc002214000, 0xc00012c400)
	/opt/local/lib/go/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0x20b43e0, 0x19d5a80, 0xc002214000, 0xc00012c400)
	/opt/local/lib/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc000149380, 0x19d5a80, 0xc002214000, 0xc00012c400)
	/opt/local/lib/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00032e1e0, 0x19d66c0, 0xc0002d6240)
	/opt/local/lib/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/opt/local/lib/go/src/net/http/server.go:2851 +0x2f5
2018/11/05 15:47:55 http: panic serving [::1]:54587: runtime error: slice bounds out of range
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc002b0a000)
	/opt/local/lib/go/src/net/http/server.go:1746 +0xd0
panic(0x16e04c0, 0x20a2fd0)
	/opt/local/lib/go/src/runtime/panic.go:513 +0x1b9
go-hep.org/x/hep/rootio.(*LeafF).scan(0xc0418b68c0, 0xc0000760c0, 0x1685a80, 0xc002b34000, 0xc002b34000, 0x16)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/leaf_gen.go:991 +0x5b3
go-hep.org/x/hep/rootio.(*tbranch).scan(0xc0418b1dc0, 0x1685a80, 0xc002b34000, 0x1685a80, 0xc002b34000)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/branch.go:389 +0x9c
go-hep.org/x/hep/rootio.(*TreeScanner).scanArgs(0xc0033da000, 0xc0000e1988, 0x1, 0x1, 0x0, 0xc002b137b8)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/scanner.go:363 +0x297
go-hep.org/x/hep/rootio.(*TreeScanner).Scan(0xc0033da000, 0xc002b13988, 0x1, 0x1, 0x0, 0x0)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/scanner.go:333 +0x9b
go-hep.org/x/hep/rootio/cmd/root-srv/server.(*server).plotBranchHandle(0xc00014ba10, 0x19d5a80, 0xc002b2e000, 0xc0003a4000, 0x0, 0x0)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/cmd/root-srv/server/plots.go:222 +0xb23
go-hep.org/x/hep/rootio/cmd/root-srv/server.(*server).plotBranchHandle-fm(0x19d5a80, 0xc002b2e000, 0xc0003a4000, 0xc0003a4000, 0x0)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/cmd/root-srv/server/server.go:42 +0x48
go-hep.org/x/hep/rootio/cmd/root-srv/server.(*server).wrap.func1(0x19d5a80, 0xc002b2e000, 0xc0003a4000)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/rootio/cmd/root-srv/server/server.go:90 +0x171
net/http.HandlerFunc.ServeHTTP(0xc000224880, 0x19d5a80, 0xc002b2e000, 0xc0003a4000)
	/opt/local/lib/go/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0x20b43e0, 0x19d5a80, 0xc002b2e000, 0xc0003a4000)
	/opt/local/lib/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc000149380, 0x19d5a80, 0xc002b2e000, 0xc0003a4000)
	/opt/local/lib/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc002b0a000, 0x19d66c0, 0xc002b16040)
	/opt/local/lib/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/opt/local/lib/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by sbinet** [comment]
hum... plotting first `Electron_mass` works... but plotting then `Electron_eta` doesn't ...

**Comment by sbinet** [comment]
and plotting twice `Electron_mass` doesn't work the second time...

**Comment by sbinet** [comment]
@vkuznet could you give #400 a try?
it works for me now :)

**Comment by vkuznet** [comment]
It works partially. By that I mean, sometimes I can get a plot and sometimes (I think if I do double click it does not). May be there is racing conditions in that case. I would suggest that you try single click vs double/triple click. It would be nice to add JS notification (spinning ball or something) that users can see that the click was done and some action on a server part is doing something.

Here is a traceback of using local file:
```
goroutine 30 [running]:
net/http.(*conn).serve.func1(0xc00037a000)
	/opt/local/lib/go/src/net/http/server.go:1746 +0xd0
panic(0x1714420, 0x2116f00)
	/opt/local/lib/go/src/runtime/panic.go:513 +0x1b9
go-hep.org/x/hep/groot/rbytes.(*RBuffer).setPos(...)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/groot/rbytes/rbuffer.go:96
go-hep.org/x/hep/groot/rbytes.(*RBuffer).SetPos(...)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/groot/rbytes/rbuffer.go:93
go-hep.org/x/hep/groot/rtree.(*Basket).loadEntry(...)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/groot/rtree/basket.go:124
go-hep.org/x/hep/groot/rtree.(*tbranch).loadEntry(0xc00080a540, 0x5606, 0x16, 0x16d3a00)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/groot/rtree/branch.go:272 +0xa5
go-hep.org/x/hep/groot/rtree.(*TreeScanner).scanArgs(0xc0000a8270, 0xc001a33800, 0x1, 0x1, 0x0, 0xc001a335f0)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/groot/rtree/scanner.go:359 +0x212
go-hep.org/x/hep/groot/rtree.(*TreeScanner).Scan(0xc0000a8270, 0xc001a33800, 0x1, 0x1, 0x0, 0x0)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/groot/rtree/scanner.go:334 +0x9b
go-hep.org/x/hep/groot/rsrv.(*Server).handlePlotTree(0xc00033c080, 0x1a1bf80, 0xc000c02000, 0xc000388200, 0x0, 0x0)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/groot/rsrv/endpoints.go:806 +0x828
go-hep.org/x/hep/groot/rsrv.(*Server).handlePlotTree-fm(0x1a1bf80, 0xc000c02000, 0xc000388200, 0xc000388200, 0x0)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/groot/rsrv/endpoints.go:725 +0x48
go-hep.org/x/hep/groot/rsrv.(*Server).wrap.func1(0x1a1bf80, 0xc000c02000, 0xc000388200)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/groot/rsrv/server.go:94 +0x171
go-hep.org/x/hep/groot/rsrv.(*Server).PlotTree(0xc00033c080, 0x1a1bf80, 0xc000c02000, 0xc000388200)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/groot/rsrv/endpoints.go:725 +0x87
go-hep.org/x/hep/groot/rsrv.(*Server).PlotTree-fm(0x1a1bf80, 0xc000c02000, 0xc000388200)
	/Users/vk/Work/Languages/Go/gopath/src/go-hep.org/x/hep/groot/cmd/root-srv/server.go:55 +0x48
net/http.HandlerFunc.ServeHTTP(0xc0003260a0, 0x1a1bf80, 0xc000c02000, 0xc000388200)
	/opt/local/lib/go/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0x21283c0, 0x1a1bf80, 0xc000c02000, 0xc000388200)
	/opt/local/lib/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc000356000, 0x1a1bf80, 0xc000c02000, 0xc000388200)
	/opt/local/lib/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00037a000, 0x1a1cc80, 0xc0000b2080)
	/opt/local/lib/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/opt/local/lib/go/src/net/http/server.go:2851 +0x2f5
^Croot-srv: shutdown sequence...
root-srv: error "/plot-branch": could not scan entry 583583 of branch "CaloMET_phi" in tree "Events" of file "/opt/cms/data/Tau_Run2017F-31Mar2018-v1_NANOAOD.root": riofs: could not decompress key payload: read /opt/cms/data/Tau_Run2017F-31Mar2018-v1_NANOAOD.root: file already closed
```

And, opening remote file seems to "work" (meaning that it tries to access the file but fail due to gsi error which is a different problem):
```
root-srv: error "/file-open": could not open ROOT file: riofs: unable to open "root://cms-xrd-global.cern.ch//store/data/Run2018C/Tau/NANOAOD/14Sep2018_ver3-v1/60000/069A01AD-A9D0-7C4E-8940-FA5990EDFFCE.root" ("xrdio: could not open \"root://cms-xrd-global.cern.ch//store/data/Run2018C/Tau/NANOAOD/14Sep2018_ver3-v1/60000/069A01AD-A9D0-7C4E-8940-FA5990EDFFCE.root\": xrootd: could not authorize:\n[xrootd: could not authorize using gsi: provider was not found]")
root-srv: error "/root-file-open": could not open file "root://cms-xrd-global.cern.ch//store/data/Run2018C/Tau/NANOAOD/14Sep2018_ver3-v1/60000/069A01AD-A9D0-7C4E-8940-FA5990EDFFCE.root"
root-srv: http: multiple response.WriteHeader calls
```

**Comment by sbinet** [comment]
wrt the second issue: yes, as I said earlier in one of the other `root-srv` related issue or PR, `GSI` is not supported. (you may want to give a friendly ping there: https://github.com/xrootd/xrootd/issues/757 to perhaps speed up the process :P)

I'll try to reproduce the race.

**Comment by sbinet** [comment]
this is now tracked by #403
