### ISSUE TITLE
Possibly strange behaviour of S2D

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#659]
I am using `hbook.DivideH1D(hData, hMC)` to create ratio plot and it seems to "freeze" the program once I add this obtained corresponding `hplot.S2D` to a `hplot.Plot`. The problem can (hopefully) be reproduced using https://github.com/rmadar/tree-gonalyzer/commit/b039fc00d21eae013cbebbc3a753b85ffcca4688 .

On my computer, the program doesn't end - it keeps running at least for a *very* long time - unless I comment the line https://github.com/rmadar/tree-gonalyzer/blob/master/ana/maker.go#L340
```go
 rp.Bottom.Add(s2d_ratio)
```

I don't know if I did something wrong or not. Sorry if this is a stupid mistake on my side.

**Comment by sbinet** [comment]
running it and then hitting `^C` while it seemed stuck gave:

```
$> ./ana-show 
before division
after division
^\SIGQUIT: quit
PC=0x470ca1 m=0 sigcode=128

goroutine 0 [idle]:
runtime.futex(0x20130c8, 0x80, 0x0, 0x0, 0x7ffc00000000, 0x4415da, 0x20121f8, 0x100000002, 0x7ffcc4a9e648, 0x41000f, ...)
	/home/binet/sdk/go/src/runtime/sys_linux_amd64.s:567 +0x21
runtime.futexsleep(0x20130c8, 0x7ffc00000000, 0xffffffffffffffff)
	/home/binet/sdk/go/src/runtime/os_linux.go:45 +0x46
runtime.notesleep(0x20130c8)
	/home/binet/sdk/go/src/runtime/lock_futex.go:159 +0x9f
runtime.stopm()
	/home/binet/sdk/go/src/runtime/proc.go:1881 +0xc4
runtime.findrunnable(0xc000046000, 0x0)
	/home/binet/sdk/go/src/runtime/proc.go:2413 +0xa0b
runtime.schedule()
	/home/binet/sdk/go/src/runtime/proc.go:2613 +0x324
runtime.park_m(0xc000001e00)
	/home/binet/sdk/go/src/runtime/proc.go:2783 +0x9d
runtime.mcall(0x0)
	/home/binet/sdk/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [runnable]:
go-hep.org/x/hep/hplot/internal/talbot.talbotLinHanrahan(0x7ff8000000000001, 0x7ff8000000000001, 0x3, 0x2, 0x0, 0x6, 0x6, 0x0, 0x10d21f0, 0x0, ...)
	/home/binet/gohack/go-hep.org/x/hep/hplot/internal/talbot/labelling.go:120 +0x547
go-hep.org/x/hep/hplot/internal/talbot.Ticks(0x7ff8000000000001, 0x7ff8000000000001, 0x3, 0x10, 0x4064a00000000000, 0x19)
	/home/binet/gohack/go-hep.org/x/hep/hplot/internal/talbot/ticks.go:23 +0x8a
go-hep.org/x/hep/hplot.Ticks.Ticks(0x3, 0x0, 0x0, 0x7ff8000000000001, 0x7ff8000000000001, 0x0, 0x0, 0x0)
	/home/binet/gohack/go-hep.org/x/hep/hplot/ticks.go:86 +0x5c
gonum.org/v1/plot.verticalAxis.size(0x7ff8000000000001, 0x7ff8000000000001, 0x0, 0x0, 0x4014000000000000, 0x1693c40, 0xc0003e9814, 0x402c000000000000, 0x10873ea, 0x9, ...)
	/home/binet/tmp/go/pkg/mod/gonum.org/v1/plot@v0.7.1-0.20200414075901-f4e1939a9e7a/axis.go:330 +0x82
gonum.org/v1/plot.(*Plot).DataCanvas(0xc00069f800, 0x16c3aa0, 0xc0000957a0, 0x4018000000000000, 0x4018000000000000, 0x407a000000000000, 0x4063e00000000000, 0x0, 0x0, 0x0, ...)
	/home/binet/tmp/go/pkg/mod/gonum.org/v1/plot@v0.7.1-0.20200414075901-f4e1939a9e7a/plot.go:186 +0x142
gonum.org/v1/plot.Align(0xc0008bcf50, 0x2, 0x2, 0x1, 0x2, 0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, ...)
	/home/binet/tmp/go/pkg/mod/gonum.org/v1/plot@v0.7.1-0.20200414075901-f4e1939a9e7a/align.go:53 +0x46c
go-hep.org/x/hep/hplot.(*RatioPlot).align(0xc0008eed80, 0x16c3aa0, 0xc0000956b0, 0x4014000000000000, 0x4014000000000000, 0x407a100000000000, 0x4073a00000000000, 0x0, 0x0, 0x0, ...)
	/home/binet/gohack/go-hep.org/x/hep/hplot/ratioplot.go:76 +0x1e1
go-hep.org/x/hep/hplot.(*RatioPlot).Draw(0xc0008eed80, 0x16c3aa0, 0xc0000956b0, 0x4014000000000000, 0x4014000000000000, 0x407a100000000000, 0x4073a00000000000)
	/home/binet/gohack/go-hep.org/x/hep/hplot/ratioplot.go:61 +0x9d
go-hep.org/x/hep/hplot.(*Fig).Draw(0xc00018eb90, 0x16c3aa0, 0xc0000956b0, 0x4014000000000000, 0x4014000000000000, 0x407a100000000000, 0x4073a00000000000)
	/home/binet/gohack/go-hep.org/x/hep/hplot/figure.go:92 +0x250
go-hep.org/x/hep/hplot.WriterTo(0x16925a0, 0xc00018eb90, 0x407b000000000000, 0x4074400000000000, 0xc0008f8032, 0x3, 0xc0008f8020, 0xc0008bd3a0, 0x453104, 0x15)
	/home/binet/gohack/go-hep.org/x/hep/hplot/io.go:115 +0x200
go-hep.org/x/hep/hplot.Save.func1(0xc0008f8020, 0x15, 0x0, 0x0)
	/home/binet/gohack/go-hep.org/x/hep/hplot/io.go:53 +0x11c
go-hep.org/x/hep/hplot.Save(0x16925a0, 0xc00018eb90, 0x407b000000000000, 0x4074400000000000, 0xc0008bd748, 0x1, 0x1, 0x107f0f5, 0x1)
	/home/binet/gohack/go-hep.org/x/hep/hplot/io.go:86 +0x102
github.com/rmadar/tree-gonalyzer/ana.(*Maker).PlotHistos(0xc0008bdeb8, 0x0, 0x0)
	/home/binet/tmp/go/src/github.com/rmadar/tree-gonalyzer/ana/maker.go:369 +0x1555

```

ie: probably some infinite loop in the tick inference.

that lead me to this "hack":
```diff
--- a/ana/maker.go
+++ b/ana/maker.go
@@ -329,12 +329,20 @@ func (ana *Maker) PlotHistos() error {
                                // Build up the ratio histo
                                //_, _ = hDataData, hTotData
                                fmt.Println("before division")
-                               s2d_ratio_data, err := hbook.DivideH1D(hDataData, hTotData)
+                               s2d_ratio_dataTMP, err := hbook.DivideH1D(hDataData, hTotData)
                                if err != nil {
                                        log.Fatal("cannot divide histo for the ratio plot")
                                }
                                fmt.Println("after division")
-                               s2d_ratio := hplot.NewS2D(s2d_ratio_data, hplot.WithYErrBars(true))
+                               var pts = make([]hbook.Point2D, 0, len(s2d_ratio_dataTMP.Points()))
+                               for i, pt := range s2d_ratio_dataTMP.Points() {
+                                       log.Printf("ratio[%d]: %#v", i, pt)
+                                       if math.IsNaN(pt.ErrY.Min) || math.IsNaN(pt.ErrY.Max) {
+                                               continue
+                                       }
+                                       pts = append(pts, pt)
+                               }
+                               s2d_ratio := hplot.NewS2D(hbook.NewS2D(pts...), hplot.WithYErrBars(true))
                                style.ApplyToDataS2D(s2d_ratio)
 
                                // Create ratio plot type
```

(there were some NaNs that were leading the talbot algorithm astray...)

**Comment by rmadar** [comment]
I see, thanks. Would it make sense to include such protections against NaN directly in the `hbook.DivideH1D()` function?

**Comment by sbinet** [comment]
I guess we could indeed do such a thing, and document as you previously did in https://github.com/go-hep/hep/pull/655/commits/da77bfddaedb6e476b96b08243d3c1e241650413

**Comment by rmadar** [comment]
OK, I'll probably soon open an PR on this then.
