### ISSUE TITLE
hplot/hstack: possible issue with LogY hstack

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#749]
I am playing with `hplot.WithLogY()` option and it works fine for `hplot.H1D`. For `hplot.Hstack`, it seems there is something odd when `HStackKind = HStackOn`. I tried to look at the hstack code, but I didn't see anything.

What I will describe here can be reproduced runing `Example_withLogScale()`, defined [here](https://github.com/rmadar/tree-gonalyzer/blob/2ac65225345f64189d8fb906270058d70700a4d2/ana/example_test.go#L131). When stack mode is off  (*i.e.* `ana.WithHistoStack(false)`), I get this:
![image](https://user-images.githubusercontent.com/30081646/83811358-f357ce80-a6b9-11ea-9d16-313a40436282.png)
(so no pb, even with bins having 0 events)

When I enable stacking (*i.e.* `ana.WithHistoStack(true)`), I get this error (which appears at the command `hplot.Save(f, ...)`):
```
panic: Values must be greater than 0 for a log scale. [recovered]
	panic: Values must be greater than 0 for a log scale.
``` 
But when I keep stack enabled and I change the x-axis ranges from `[0, 3000]` to [350, 2000], it works:
![image](https://user-images.githubusercontent.com/30081646/83811674-87299a80-a6ba-11ea-8ee8-ed7b0d71bf68.png)

**Comment by sbinet** [comment]
it would seem it's when plotting the `Band` that things go awry...

```
=== RUN   Example_withLogScale
--- FAIL: Example_withLogScale (0.40s)
panic: Values must be greater than 0 for a log scale. [recovered]
	panic: Values must be greater than 0 for a log scale.

goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0xc0001efd28, 0x0, 0x0, 0x17f6a04c, 0xba9240, 0xe8d3b0, 0x20300000000000)
	/home/binet/sdk/go/src/testing/example.go:89 +0x648
testing.runExample.func2(0xbfae9c15d598747e, 0x71c4fd, 0x1478fc0, 0xc0000ac590, 0xc0000ac008, 0xc0000942a0, 0xc00023fd28, 0xc0001efd58)
	/home/binet/sdk/go/src/testing/run_example.go:58 +0x10d
panic(0xba9240, 0xe8d3b0)
	/home/binet/sdk/go/src/runtime/panic.go:969 +0x175
gonum.org/v1/plot.LogScale.Normalize(0x3fd0000000000000, 0x40bd5f0000000000, 0x0, 0x7efdb7682cd0)
	/home/binet/tmp/go/pkg/mod/gonum.org/v1/plot@v0.7.1-0.20200602093449-6d232e045386/axis.go:192 +0xda
gonum.org/v1/plot.Axis.Norm(...)
	/home/binet/tmp/go/pkg/mod/gonum.org/v1/plot@v0.7.1-0.20200602093449-6d232e045386/axis.go:214
gonum.org/v1/plot.(*Plot).Transforms.func2(0x0, 0x40533df19999999a)
	/home/binet/tmp/go/pkg/mod/gonum.org/v1/plot@v0.7.1-0.20200602093449-6d232e045386/plot.go:318 +0xb4
gonum.org/v1/plot/plotter.(*Polygon).Plot(0xc0001ed4d8, 0xebcf60, 0xc00031c300, 0x40533df19999999a, 0x4059c66666666667, 0x40793c3c00000000, 0x40711ac227448df4, 0xc0003dec00)
	/home/binet/tmp/go/pkg/mod/gonum.org/v1/plot@v0.7.1-0.20200602093449-6d232e045386/plotter/polygon.go:62 +0x1b9
go-hep.org/x/hep/hplot.(*Band).Plot(0xc0008d9000, 0xebcf60, 0xc00031c300, 0x40533df19999999a, 0x4059c66666666667, 0x40793c3c00000000, 0x40711ac227448df4, 0xc0003dec00)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/hplot/band.go:72 +0x2e9
go-hep.org/x/hep/hplot.(*HStack).hplot(0xc00007fdd0, 0xebcf60, 0xc00031c300, 0x40533df19999999a, 0x4059c66666666667, 0x40793c3c00000000, 0x40711ac227448df4, 0xc0003dec00, 0xc000df9320, 0xc00002e0f0, ...)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/hplot/hstack.go:258 +0xf0d
go-hep.org/x/hep/hplot.(*HStack).Plot(0xc00007fdd0, 0xebcf60, 0xc00031c300, 0x40533df19999999a, 0x4059c66666666667, 0x40793c3c00000000, 0x40711ac227448df4, 0xc0003dec00)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/hplot/hstack.go:159 +0x13e
gonum.org/v1/plot.(*Plot).Draw(0xc0003dec00, 0xebcf60, 0xc00031c2d0, 0x4018000000000000, 0x40572ccccccccccd, 0x40793c3c00000000, 0x4071678000000000)
	/home/binet/tmp/go/pkg/mod/gonum.org/v1/plot@v0.7.1-0.20200602093449-6d232e045386/plot.go:168 +0x949
go-hep.org/x/hep/hplot.(*Plot).Draw(...)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/hplot/plot.go:97
go-hep.org/x/hep/hplot.(*RatioPlot).Draw(0xc000491a40, 0xebcf60, 0xc00009a600, 0x4014000000000000, 0x4014000000000000, 0x407a100000000000, 0x4073a00000000000)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/hplot/ratioplot.go:64 +0x1bc
go-hep.org/x/hep/hplot.(*Fig).Draw(0xc00048a3c0, 0xebcf60, 0xc00009a600, 0x4014000000000000, 0x4014000000000000, 0x407a100000000000, 0x4073a00000000000)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/hplot/figure.go:92 +0x250
go-hep.org/x/hep/hplot.WriterTo(0xe99c40, 0xc00048a3c0, 0x407b000000000000, 0x4074400000000000, 0xc000b7dc40, 0x3, 0xc000b7dc20, 0xc00023e758, 0x452ef4, 0x23)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/hplot/io.go:115 +0x203
go-hep.org/x/hep/hplot.Save.func1(0xc000b7dc20, 0x23, 0x0, 0x0)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/hplot/io.go:53 +0x11c
go-hep.org/x/hep/hplot.Save(0xe99c40, 0xc00048a3c0, 0x407b000000000000, 0x4074400000000000, 0xc0001eec00, 0x1, 0x1, 0xc7e4f5, 0x1)
	/home/binet/dev/hepsw/go/src/go-hep.org/x/hep/hplot/io.go:86 +0x10b
github.com/rmadar/tree-gonalyzer/ana.(*Maker).PlotVariables(0xc000114f00, 0x0, 0x0)
	/home/binet/tmp/go/src/github.com/rmadar/tree-gonalyzer/ana/maker.go:786 +0x1859
github.com/rmadar/tree-gonalyzer/ana.(*Maker).Run(0xc000114f00, 0x4, 0x4)
	/home/binet/tmp/go/src/github.com/rmadar/tree-gonalyzer/ana/maker.go:859 +0x69
github.com/rmadar/tree-gonalyzer/ana_test.Example_withLogScale()
	/home/binet/tmp/go/src/github.com/rmadar/tree-gonalyzer/ana/example_test.go:158 +0x7ce
testing.runExample(0xc91a0a, 0x14, 0xcb7c20, 0x0, 0x0, 0x0, 0x0)
	/home/binet/sdk/go/src/testing/run_example.go:62 +0x209
testing.runExamples(0xc0001efed0, 0x1473300, 0x7, 0x7, 0xbfae9cabd5964583)
	/home/binet/sdk/go/src/testing/example.go:44 +0x1af
testing.(*M).Run(0xc000141900, 0x0)
	/home/binet/sdk/go/src/testing/testing.go:1339 +0x2cd
main.main()
	_testmain.go:79 +0x138
exit status 2
FAIL	github.com/rmadar/tree-gonalyzer/ana	0.416s
```

**Comment by rmadar** [comment]
Ok and I am tempted to say 'of course' ;-) ! I'll have a look and submit a PR. Thanks for the hint.

**Comment by sbinet** [comment]
working on it... (I have a fix)

**Comment by rmadar** [comment]
haa cool, thanks !
