### ISSUE TITLE
`segmentation violation` with xrootd client upon `Invalid or incomplete multibyte or wide character`

### ISSUE THREAD

**Issue by beer4duke** [go-hep/hep#758]
Looks like something wrong is taking place when sending plenty of files with invalid xrootd characters.

After a few of these I am getting a SIGSEGV error and the culprit part of the code seems to be in the xrootd go client.

```
2020-06-17 11:18:40 ERROR : go/pkg/mod/github.com/!unknwon/goconfig@v0.0.0-20191126170842-
860a72fb44fd/write.go: Failed to copy: xrootd: error 3022: Unable to accept path name - illegal 
characters - use only A-Z a-z 0-9 / SPACE .-_~#:^ 
/eos/myinstance/tmp/testic4/go/pkg/mod/github.com/!unknwon/goconfig@v0.0.0-20191126170842-
860a72fb44fd/write.go; Invalid or incomplete multibyte or wide character
...
<few more like this one>
```

then:
```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18df1cd]

goroutine 68 [running]:
go-hep.org/x/hep/xrootd.(*Client).Close(0x0, 0x0, 0x0)
        /root/go/pkg/mod/go-hep.org/x/hep@v0.26.0/xrootd/client.go:98 +0x5d
panic(0x1c800c0, 0x2efb510)
        /root/sdk/go/src/runtime/panic.go:969 +0x166
go-hep.org/x/hep/xrootd.(*Client).Send(...)
        /root/go/pkg/mod/go-hep.org/x/hep@v0.26.0/xrootd/client.go:118
go-hep.org/x/hep/xrootd.(*fileSystem).Open(0xc001b4c200, 0x2296140, 0xc0004be2c0, 0x0, 0x0, 0x10801ed, 0x0, 0x0, 0x2262820, 0xc0003ebe40)
        /root/go/pkg/mod/go-hep.org/x/hep@v0.26.0/xrootd/filesystem.go:47 +0xb2
github.com/rclone/rclone/backend/xrootd.(*Object).Update(0xc000a4a3c0, 0x2296140, 0xc0004be2c0, 0x2263ae0, 0xc0011ae000, 0x7f78f85ec838, 0xc0008394a0, 0xc0004408a0, 0x1, 0x1, ...)
        /root/sdk/rclone/backend/xrootd/xrootd.go:860 +0x285
github.com/rclone/rclone/backend/xrootd.(*Fs).Put(0xc000507ce0, 0x2296140, 0xc0004be2c0, 0x2263ae0, 0xc0011ae000, 0x7f78f85ec838, 0xc0008394a0, 0xc0004408a0, 0x1, 0x1, ...)
        /root/sdk/rclone/backend/xrootd/xrootd.go:549 +0x193
github.com/rclone/rclone/fs/operations.Copy(0x2296140, 0xc0004be2c0, 0x22adec0, 0xc000507ce0, 0x0, 0x0, 0xc001b3c7e0, 0x2c, 0x22acd40, 0xc0008394a0, ...)
        /root/sdk/rclone/fs/operations/operations.go:432 +0x158f
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc00003e380, 0x2296140, 0xc0004be2c0, 0xc000220960, 0x22adec0, 0xc000507ce0, 0x0, 0xc00003e458)
        /root/sdk/rclone/fs/sync/sync.go:358 +0x223
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers
        /root/sdk/rclone/fs/sync/sync.go:385 +0xd2
```

I have attached the logs of a failed rclone session.
[sigsegv.log](https://github.com/go-hep/hep/files/4791548/sigsegv.log)

**Comment by sbinet** [comment]
thanks for the report.
could you also specify an (as minimal as possible) reproducer so I could try to debug this?

the panic seems to come from:
https://github.com/go-hep/hep/blob/v0.26.0/xrootd/client.go#L98
indicating the `Client` receiver is a `nil` value.

**Comment by beer4duke** [comment]
Looks like the name errors are not responsible for this `SIGSEGV`.

It only occurs when I try to send a large amount of files via xrootd:
```
Transferred:      675.212M / 1.235 GBytes, 53%, 10.019 MBytes/s, ETA 58s
Errors:                 8 (retrying may help)
Transferred:         3402 / 13411, 25%
Elapsed time:       1m7.3s
Transferring:
```

**Comment by sbinet** [comment]
in the meantime, could you also tell me with which revision of https://github.com/beer4all/rclone/blob/xrootd-devel/backend/xrootd/xrootd.go the SIGSEV log above was obtained?
(not sure that https://github.com/beer4all/rclone/commit/9ba5d1e657c3aa2171cfa8acbeec227b9c163425 matches what was attached above)

**Comment by sbinet** [comment]
ok...
it's probably coming from:
https://github.com/beer4all/rclone/blob/9ba5d1e657c3aa2171cfa8acbeec227b9c163425/backend/xrootd/xrootd.go#L850...L854
```go
	client,path,removeErr :=o.fs.xrdremote(o.path(),ctx)
	if removeErr != nil{
		fs.Debugf(src, "Failed to open client", removeErr)
	}
	defer client.Close()
```

ie: `xrdremote` returns a `(nil-client, non-nil-error)`.
the error is checked but the execution flow continues instead of returning (or taking actions to mitigate that error.)

there is another one here:
https://github.com/beer4all/rclone/blob/9ba5d1e657c3aa2171cfa8acbeec227b9c163425/backend/xrootd/xrootd.go#L871

**Comment by sbinet** [comment]
in the spirit of "belt and suspenders", https://github.com/go-hep/hep/pull/759 should also cure that particular segfault.

**Comment by beer4duke** [comment]
I tried with latest commit aa37c691 and I am still getting a SIGSEGV:
```
Transferred:       43.120M / 79.049 MBytes, 55%, 45.126 MBytes/s, ETA 0s
Checks:              2530 / 2530, 100%
Transferred:          215 / 219, 98%
Elapsed time:         0.9s
Transferring:
 *                             sdk/rclone/rclone: 35% /55.925M, 0/s, -
 * CTA/.git/objects/f7/0d…5a04e4c490577e5537d013:100% /46, 0/s, -
 * CTA/.git/objects/f7/41…26e86ee324dd7c8216143c:100% /53, 0/s, -
 * CTA/.git/objects/f7/64…a1f02ef875d5338b52bb2a:100% /4.266k, 0/s, -panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x18e2862]

goroutine 84 [running]:
go-hep.org/x/hep/xrootd.(*Client).Send(...)
        /root/go/pkg/mod/go-hep.org/x/hep@v0.27.1-0.20200622082015-aa37c691264e/xrootd/client.go:123
go-hep.org/x/hep/xrootd.(*fileSystem).Open(0xc0006a8248, 0x2298000, 0xc00015e0c0, 0x0, 0x0, 0x10801ed, 0x0, 0x0, 0x22645e0, 0xc0011c3580)
        /root/go/pkg/mod/go-hep.org/x/hep@v0.27.1-0.20200622082015-aa37c691264e/xrootd/filesystem.go:47 +0xb2
github.com/rclone/rclone/backend/xrootd.(*Object).Update(0xc002919180, 0x2298000, 0xc00015e0c0, 0x22658a0, 0xc0011d2000, 0x7f5bc1a50010, 0xc000827e60, 0xc000452080, 0x1, 0x1, ...)
        /root/sdk/rclone/backend/xrootd/xrootd.go:860 +0x285
github.com/rclone/rclone/backend/xrootd.(*Fs).Put(0xc000500310, 0x2298000, 0xc00015e0c0, 0x22658a0, 0xc0011d2000, 0x7f5bc1a50010, 0xc000827e60, 0xc000452080, 0x1, 0x1, ...)
        /root/sdk/rclone/backend/xrootd/xrootd.go:549 +0x193
github.com/rclone/rclone/fs/operations.Copy(0x2298000, 0xc00015e0c0, 0x22afe00, 0xc000500310, 0x0, 0x0, 0xc0016dccc0, 0x2c, 0x22aec80, 0xc000827e60, ...)
        /root/sdk/rclone/fs/operations/operations.go:432 +0x158f
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc00012a8c0, 0x2298000, 0xc00015e0c0, 0xc00009c230, 0x22afe00, 0xc000500310, 0x19, 0xc00012a998)
        /root/sdk/rclone/fs/sync/sync.go:358 +0x223
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers
        /root/sdk/rclone/fs/sync/sync.go:385 +0xd2
```

**Comment by sbinet** [comment]
thanks for the report.

this seems to still point to trying to use a `nil` `*xrootd.Client` value.
(I'll add another nil-check in `xrootd.Client.Send`, but this also probably means that your `rclone` branch hasn't been fixed as I indicated in https://github.com/go-hep/hep/issues/758#issuecomment-645852251 :P)

**Comment by sbinet** [comment]
https://github.com/go-hep/hep/pull/765 should address that particular segfault.

**Comment by beer4duke** [comment]
Indeed @sbinet the backend code should be mode defensive...
But in the meantime I tested again with b0b8bd0b and no more SIGSEGV error.

I am closing this issue (and opening a new one for the rclone xrootd backend for its strange error handling (or lack of it)...
Thanks again!
