### ISSUE TITLE
groot/rtree: vector<float> failing with rtree.reader but working with rtree.Scanner

### ISSUE THREAD

**Issue by rmadar** [go-hep/hep#786]
I have meet a weird problem, a bit like the one discussed in https://github.com/go-hep/hep/issues/781, which occurs only with `rtree.Reader` since it works fine with `rtree.Scanner`. More precisely, I have the following error: 
```
panic: rtree: could not create rstreamer for rleaf "d_lep_pt"

goroutine 1 [running]:
go-hep.org/x/hep/groot/rtree.newRLeafElem(0xc000253520, 0x8704dd, 0x8, 0x8704dd, 0x8, 0x7c9dc0, 0xc0002c2820, 0x0, 0x0, 0xcbfe80, ...)
	/users/divers/atlas/madar/go/pkg/mod/go-hep.org/x/hep@v0.27.1-0.20200725171723-7d2c4375757a/groot/rtree/rleaf.go:165 +0x83b
go-hep.org/x/hep/groot/rtree.rleafFrom(0xcbfe80, 0xc000253520, 0x8704dd, 0x8, 0x8704dd, 0x8, 0x7c9dc0, 0xc0002c2820, 0x0, 0x0, ...)
	/users/divers/atlas/madar/go/pkg/mod/go-hep.org/x/hep@v0.27.1-0.20200725171723-7d2c4375757a/groot/rtree/rleaf.go:122 +0x7eb
go-hep.org/x/hep/groot/rtree.newRTree(0xc0000fa600, 0xc0001a0640, 0x2, 0x2, 0x2, 0x0, 0x2c, 0x2)
	/users/divers/atlas/madar/go/pkg/mod/go-hep.org/x/hep@v0.27.1-0.20200725171723-7d2c4375757a/groot/rtree/reader.go:310 +0x403
go-hep.org/x/hep/groot/rtree.newReader(0xcaf020, 0xc0000fa600, 0xc0001a0640, 0x2, 0x2, 0x2, 0x0, 0x2c, 0x0, 0x0)
	/users/divers/atlas/madar/go/pkg/mod/go-hep.org/x/hep@v0.27.1-0.20200725171723-7d2c4375757a/groot/rtree/reader.go:255 +0x13b
go-hep.org/x/hep/groot/rtree.NewReader(0xcaf020, 0xc0000fa600, 0xc0001a0640, 0x2, 0x2, 0x0, 0x0, 0x0, 0x7, 0x1, ...)
	/users/divers/atlas/madar/go/pkg/mod/go-hep.org/x/hep@v0.27.1-0.20200725171723-7d2c4375757a/groot/rtree/reader.go:66 +0x206
main.withReader(0xcaf020, 0xc0000fa600)
	/users/divers/atlas/madar/home2/tmp/gotest/main.go:77 +0x12f
main.main()
	/users/divers/atlas/madar/home2/tmp/gotest/main.go:28 +0x158

```

Here are a minimal example and a test input file:
 + root file (15 Mo): https://cernbox.cern.ch/index.php/s/yJ6Sr9kzDuNJ7mC
 + code:
```go
func main(){                                                 
                                                             
        // Open ROOT file                                    
        fName := "treeFailingReader.root"                    
        f, err := groot.Open(fName)                          
        if err != nil {                                      
                log.Fatal(err)                               
        }                                                    
                                                             
        // Get the tree                                    
        obj, err := f.Get("nominal")                         
        if err != nil {                                      
                log.Fatal(err)                               
        }                                                    
        tree := obj.(rtree.Tree)                             
                                                             
        // Crashes with reader                               
        withReader(tree)                                     
                                                             
        // Works fine with scanner                           
        withScanner(tree)                                    
}  

func withReader(tree rtree.Tree) {                                               
                                                                                 
        // Defined variables to read                                             
        var (                                                                    
                pt []float32                                                     
                e []float32                                                      
                rvars = []rtree.ReadVar{                                         
                        {Name: "d_lep_pt", Value: &pt},                          
                        {Name: "d_lep_e" , Value: &e},                           
                }                                                                
        )                                                                        
                                                                                 
        // Create a reader                                                       
        r, err := rtree.NewReader(tree, rvars)                                   
        if err != nil {                                                          
                log.Fatalf("could not create tree reader: %+v", err)             
        }                                                                        
        defer r.Close()                                                          
                                                                                 
        // Loop over entries reader                                              
        err = r.Read(func(ctx rtree.RCtx) error {                                
                fmt.Println(e, pt)                                               
                return nil                                                       
        })                                                                       
                                                                                 
}

 func withScanner(tree rtree.Tree) {                                              
                                                                                 
        var (                                                                    
                pt []float32                                                     
                e []float32                                                      
                svars = []rtree.ScanVar{                                         
                        {Name: "d_lep_pt", Value: &pt},                          
                        {Name: "d_lep_e" , Value: &e},                           
                }                                                                
        )                                                                        
                                                                                 
        sc, err := rtree.NewScannerVars(tree, svars...)                          
        if err != nil {                                                          
                log.Fatalf("could not create tree scanner: %+v", err)            
        }                                                                        
        defer sc.Close()                                                         
                                                                                 
        // Loop over entries: scanner                                            
        for sc.Next() {                                                          
                                                                                 
                err := sc.Scan()                                                 
                if err != nil {                                                  
                        log.Fatal(err)                                           
                }                                                                
                                                                                 
                fmt.Println(e, pt)                                               
        }                                                                        
} 
```

**Comment by sbinet** [comment]
could you test with #801?

it works for me.

**Comment by rmadar** [comment]
ha great thanks! I am a bit busy these days so it might take few days, but I'll do!

**Comment by rmadar** [comment]
I know this is solved since a while, but I just tried in my use-case and it works also fine!
