### ISSUE TITLE
cmd/root2npy: add support for writing empty slices

### ISSUE THREAD

**Issue by sbinet** [go-hep/hep#891]
as reported in:
https://root-forum.cern.ch/t/convert-root-file-to-something-readable-by-python/48262/16

```
root2npy: scanning leaves...
root2npy: scanning leaves... [done]
root2npy: could not get shape from []float32: []
err: reflect: slice index out of range
panic: reflect: slice index out of range [recovered]
	panic: reflect: slice index out of range

goroutine 1 [running]:
github.com/sbinet/npyio/npy.shapeFrom.func1()
	/home/binet/work/gonum/src/github.com/sbinet/npyio/npy/writer.go:528 +0x125
panic({0xb00d20, 0xdff530})
	/home/binet/sdk/go/src/runtime/panic.go:838 +0x207
reflect.Value.Index({0xaf5520?, 0xc00000c828?, 0x2?}, 0xc000026e98?)
	/home/binet/sdk/go/src/reflect/value.go:1366 +0x16d
github.com/sbinet/npyio/npy.shapeFrom({0xaf5520?, 0xc00000c828?, 0x42eed6?})
	/home/binet/work/gonum/src/github.com/sbinet/npyio/npy/writer.go:531 +0x205
github.com/sbinet/npyio/npy.Write({0xdffee0, 0xc0001c9710}, {0xaf5520?, 0xc00000c828?})
	/home/binet/work/gonum/src/github.com/sbinet/npyio/npy/writer.go:41 +0x1a7
github.com/sbinet/npyio.Write(...)
	/home/binet/work/gonum/src/github.com/sbinet/npyio/npyio.go:125
main.process({0x7ffd31cb37df, 0x4b}, {0x7ffd31cb3784, 0x4d}, {0x7ffd31cb37d5, 0x6})
	/home/binet/work/gonum/src/go-hep.org/x/hep/cmd/root2npy/main.go:225 +0xb69
main.main()
	/home/binet/work/gonum/src/go-hep.org/x/hep/cmd/root2npy/main.go:160 +0x185
```

this is filed as https://github.com/sbinet/npyio/issues/15

**Comment by Jatharachill** [comment]
Hey it's tmikhail. I've turned on notifications for this thread so let me know if you need me to test anything

**Comment by sbinet** [comment]
could you download and test with:

- https://cern.ch/binet/root2npy-verbose-2

thanks.

**Comment by Jatharachill** [comment]
It seems to work! the npz file was created and seems to have the correct data.
` ./root2npy-verbose-2 -f /home/octopus/Documents/Work/Thesis/Data/
ColliderSimulation/LHC1/test023.root -t GammaC -o /home/octopus/Documents/Work/Thesis/Data/ColliderSimulation/LHC1/output.npz
root2npy: scanning leaves...
root2npy: scanning leaves... [done]
`
I can't thank you enough for all your help. You've been a lifesaver

**Comment by sbinet** [comment]
cool!

I'll cut a new release with the fix.
